POST http://localhost:8080/events
content-type: application/json

{
    "title": "Test Event",
    "description": "This is a test event",
    "location": "Test Location",
    "dateTime": "2021-12-31T23:59:59.999Z"
}
